[package]
name = "transmission-rpc"
version = "0.4.3"
authors = ["red <red.avtovo@gmail.com>"]
edition = "2021"
repository = "https://github.com/j0rsa/transmission-rpc"
license = "MIT"
readme = "README.md"
description = "Transmission JRPC client"
keywords = ["transmission", "torrent", "jrpc"]
categories = ["api-bindings"]
include = ["**/*.rs", "Cargo.toml"]

[features]
# Enables use of request types as keys in HashMaps, HashSet, etc.
hashable-request = ["dep:ordered-float"]
# Enables a thread-safe version of TransClient.
sync = []
# Enables Serialization and Deserialization of `TorrentGetField`s.
tor-get-serde = []

[dependencies]
reqwest = { version = "0.12.5", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.17"
enum-iterator = "2.1.0"
chrono = {version = "0.4.31", features = ["serde"] }
jsonrpc_macros = { path = "jsonrpc_macros" }

log = "0.4.20"
bitflags = "2.10.0"
base64 = "0.22.1"
ordered-float = { version = "4.3.0", features = ["serde"], optional = true }
semver = "1.0.27"

[dev-dependencies]
env_logger = "0.11.3"
dotenvy = "0.15.7"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
