//! This file defines [`Peer`] field sub-type deserialization tests.

use std::net::Ipv4Addr;

use test_case::test_case;

use super::*;

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy ok"
)]

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 0,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 0,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy bytes to client zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 0,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 0,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy bytes to peer zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy client name empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy flag str empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy peer id empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":0,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 0,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy port zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy progress zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":1,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 1.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy progress one"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":-1,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: -1.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "legacy progress negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":0,
        "rateToPeer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 0,
        rate_to_peer: 3,
    } ; "legacy rate to client zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":0
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 0,
    } ; "legacy rate to peer zero"
)]

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": -1,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "legacy bytes to client negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": -1,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "legacy bytes to peer negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":-1,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":3
    }"# => panics "invalid value: integer `-1`, expected u16"
    ; "legacy port negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":-1,
        "rateToPeer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "legacy rate to client negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytesToClient": 12345,
        "bytesToPeer": 6,
        "clientIsChoked":false,
        "clientIsInterested":true,
        "clientName":"qBittorrent 4.6.5",
        "flagStr":"TDI",
        "isDownloadingFrom":true,
        "isEncrypted":false,
        "isIncoming":true,
        "isUploadingTo":false,
        "isUtp":true,
        "peerId":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peerIsChoked":true,
        "peerIsInterested":false,
        "port":36667,
        "progress":0.666,
        "rateToClient":8000,
        "rateToPeer":-1
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "legacy rate to peer negative"
)]

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 ok"
)]

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 0,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 0,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 bytes to client zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 0,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 0,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 bytes to peer zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 client name empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 flag str empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 peer id empty"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":0,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 0,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 port zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 progress zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":1,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 1.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 progress one"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":-1,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: -1.,
        rate_to_client: 8000,
        rate_to_peer: 3,
    } ; "semver 6.0.0 progress negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":0,
        "rate_to_peer":3
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 0,
        rate_to_peer: 3,
    } ; "semver 6.0.0 rate to client zero"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":0
    }"# => Peer {
        address: IpAddr::V4(Ipv4Addr::from_octets([127, 0, 0, 1])),
        bytes_to_client: 12345,
        bytes_to_peer: 6,
        client_is_choked: false,
        client_is_interested: true,
        client_name: "qBittorrent 4.6.5".into(),
        flag_str: "TDI".into(),
        is_downloading_from: true,
        is_encrypted: false,
        is_incoming: true,
        is_uploading_to: false,
        is_utp: true,
        peer_id: "IoxddjPhaC1vb0toOUdUTGhvbzc=".into(),
        peer_is_choked: true,
        peer_is_interested: false,
        port: 36667,
        progress: 0.666,
        rate_to_client: 8000,
        rate_to_peer: 0,
    } ; "semver 6.0.0 rate to peer zero"
)]

#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": -1,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "semver 6.0.0 bytes to client negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": -1,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "semver 6.0.0 bytes to peer negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":-1,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":3
    }"# => panics "invalid value: integer `-1`, expected u16"
    ; "semver 6.0.0 port negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":-1,
        "rate_to_peer":3
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "semver 6.0.0 rate to client negative"
)]
#[test_case(
    r#"{
        "address": "127.0.0.1",
        "bytes_to_client": 12345,
        "bytes_to_peer": 6,
        "client_is_choked":false,
        "client_is_interested":true,
        "client_name":"qBittorrent 4.6.5",
        "flag_str":"TDI",
        "is_downloading_from":true,
        "is_encrypted":false,
        "is_incoming":true,
        "is_uploading_to":false,
        "is_utp":true,
        "peer_id":"IoxddjPhaC1vb0toOUdUTGhvbzc=",
        "peer_is_choked":true,
        "peer_is_interested":false,
        "port":36667,
        "progress":0.666,
        "rate_to_client":8000,
        "rate_to_peer":-1
    }"# => panics "invalid value: integer `-1`, expected u64"
    ; "semver 6.0.0 rate to peer negative"
)]
fn peer_deserialize(peer_data: &str) -> Peer {
    match serde_json::from_str(peer_data) {
        Ok(peer) => peer,
        Err(err) => panic!("{err}"),
    }
}

